// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Accordion from "./islands/Accordion.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $AddToCartBuyTogether from "./islands/AddToCartBuyTogether.tsx";
import * as $ClearFiltersButton from "./islands/ClearFiltersButton.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $DepartamentName from "./islands/DepartamentName.tsx";
import * as $Dropdown from "./islands/Dropdown.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_HeaderFixed from "./islands/Header/HeaderFixed.tsx";
import * as $Header_Login from "./islands/Header/Login.tsx";
import * as $Header_NavItem from "./islands/Header/NavItem.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $Iframe from "./islands/Iframe.tsx";
import * as $ImageHovered from "./islands/ImageHovered.tsx";
import * as $ImageSlider from "./islands/ImageSlider.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NextButton from "./islands/NextButton.tsx";
import * as $NextButtonShelf from "./islands/NextButtonShelf.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PrevButton from "./islands/PrevButton.tsx";
import * as $PrevButtonShelf from "./islands/PrevButtonShelf.tsx";
import * as $ProductAttachment from "./islands/ProductAttachment.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductInfo from "./islands/ProductInfo.tsx";
import * as $ProductVariantSelector from "./islands/ProductVariantSelector.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $TabItem from "./islands/TabItem.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Accordion.tsx": $Accordion,
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/AddToCartBuyTogether.tsx": $AddToCartBuyTogether,
    "./islands/ClearFiltersButton.tsx": $ClearFiltersButton,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/DepartamentName.tsx": $DepartamentName,
    "./islands/Dropdown.tsx": $Dropdown,
    "./islands/Filters.tsx": $Filters,
    "./islands/Header.tsx": $Header,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/HeaderFixed.tsx": $Header_HeaderFixed,
    "./islands/Header/Login.tsx": $Header_Login,
    "./islands/Header/NavItem.tsx": $Header_NavItem,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/Iframe.tsx": $Iframe,
    "./islands/ImageHovered.tsx": $ImageHovered,
    "./islands/ImageSlider.tsx": $ImageSlider,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NextButton.tsx": $NextButton,
    "./islands/NextButtonShelf.tsx": $NextButtonShelf,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PrevButton.tsx": $PrevButton,
    "./islands/PrevButtonShelf.tsx": $PrevButtonShelf,
    "./islands/ProductAttachment.tsx": $ProductAttachment,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductInfo.tsx": $ProductInfo,
    "./islands/ProductVariantSelector.tsx": $ProductVariantSelector,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/TabItem.tsx": $TabItem,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
