// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/getProductAttachments.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/AboutUs/AboutUs.tsx";
import * as $$$$$$55 from "./sections/aboutUsPage/Advantages.tsx";
import * as $$$$$$56 from "./sections/aboutUsPage/BannerFull.tsx";
import * as $$$$$$57 from "./sections/aboutUsPage/Founder.tsx";
import * as $$$$$$58 from "./sections/aboutUsPage/Header.tsx";
import * as $$$$$$59 from "./sections/aboutUsPage/Newsletter.tsx";
import * as $$$$$$1 from "./sections/BannerMosaic/BannerMosaic.tsx";
import * as $$$$$$3 from "./sections/Banners/Banners.tsx";
import * as $$$$$$2 from "./sections/BannerVariant/BannerVariant.tsx";
import * as $$$$$$4 from "./sections/ButtonBackToTopMobile/ButtonBackToTopMobile.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$7 from "./sections/Category/SeoText.tsx";
import * as $$$$$$8 from "./sections/Content/Benefits.tsx";
import * as $$$$$$9 from "./sections/Content/Brands.tsx";
import * as $$$$$$10 from "./sections/Content/Faq.tsx";
import * as $$$$$$11 from "./sections/Content/Logos.tsx";
import * as $$$$$$12 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$13 from "./sections/Footer/Footer.tsx";
import * as $$$$$$14 from "./sections/Gallery.tsx";
import * as $$$$$$15 from "./sections/Header/Header.tsx";
import * as $$$$$$16 from "./sections/Iframe/Iframe.tsx";
import * as $$$$$$17 from "./sections/Images/Banner.tsx";
import * as $$$$$$18 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$19 from "./sections/Images/Carousel.tsx";
import * as $$$$$$20 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$21 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$22 from "./sections/Institutional/AsideMenu.tsx";
import * as $$$$$$23 from "./sections/Institutional/Institutional.tsx";
import * as $$$$$$24 from "./sections/Institutional/InstitutionalContent.tsx";
import * as $$$$$$25 from "./sections/Layout/Container.tsx";
import * as $$$$$$26 from "./sections/Layout/Flex.tsx";
import * as $$$$$$27 from "./sections/Layout/Grid.tsx";
import * as $$$$$$28 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$29 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$30 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$31 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$32 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$33 from "./sections/Miscellaneous/Form.tsx";
import * as $$$$$$34 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$35 from "./sections/Product/BuyTogether.tsx";
import * as $$$$$$36 from "./sections/Product/FeaturedProductShelf.tsx";
import * as $$$$$$37 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$38 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$39 from "./sections/Product/NotFound.tsx";
import * as $$$$$$40 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$41 from "./sections/Product/ProductAttachments.tsx";
import * as $$$$$$42 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$43 from "./sections/Product/ProductFlag.tsx";
import * as $$$$$$44 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$45 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$46 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$47 from "./sections/Product/ProductSpecifications.tsx";
import * as $$$$$$48 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$49 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$51 from "./sections/SeoText/SeoText.tsx";
import * as $$$$$$50 from "./sections/SeoTextAndBanner/SeoTextAndBanner.tsx";
import * as $$$$$$52 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$53 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$54 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/interdental/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/interdental/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/interdental/sections/AboutUs/AboutUs.tsx": $$$$$$0,
    "deco-sites/interdental/sections/aboutUsPage/Advantages.tsx": $$$$$$55,
    "deco-sites/interdental/sections/aboutUsPage/BannerFull.tsx": $$$$$$56,
    "deco-sites/interdental/sections/aboutUsPage/Founder.tsx": $$$$$$57,
    "deco-sites/interdental/sections/aboutUsPage/Header.tsx": $$$$$$58,
    "deco-sites/interdental/sections/aboutUsPage/Newsletter.tsx": $$$$$$59,
    "deco-sites/interdental/sections/BannerMosaic/BannerMosaic.tsx": $$$$$$1,
    "deco-sites/interdental/sections/Banners/Banners.tsx": $$$$$$3,
    "deco-sites/interdental/sections/BannerVariant/BannerVariant.tsx": $$$$$$2,
    "deco-sites/interdental/sections/ButtonBackToTopMobile/ButtonBackToTopMobile.tsx":
      $$$$$$4,
    "deco-sites/interdental/sections/Category/CategoryBanner.tsx": $$$$$$5,
    "deco-sites/interdental/sections/Category/CategoryList.tsx": $$$$$$6,
    "deco-sites/interdental/sections/Category/SeoText.tsx": $$$$$$7,
    "deco-sites/interdental/sections/Content/Benefits.tsx": $$$$$$8,
    "deco-sites/interdental/sections/Content/Brands.tsx": $$$$$$9,
    "deco-sites/interdental/sections/Content/Faq.tsx": $$$$$$10,
    "deco-sites/interdental/sections/Content/Logos.tsx": $$$$$$11,
    "deco-sites/interdental/sections/Content/Testimonials.tsx": $$$$$$12,
    "deco-sites/interdental/sections/Footer/Footer.tsx": $$$$$$13,
    "deco-sites/interdental/sections/Gallery.tsx": $$$$$$14,
    "deco-sites/interdental/sections/Header/Header.tsx": $$$$$$15,
    "deco-sites/interdental/sections/Iframe/Iframe.tsx": $$$$$$16,
    "deco-sites/interdental/sections/Images/Banner.tsx": $$$$$$17,
    "deco-sites/interdental/sections/Images/BannerGrid.tsx": $$$$$$18,
    "deco-sites/interdental/sections/Images/Carousel.tsx": $$$$$$19,
    "deco-sites/interdental/sections/Images/ImageGallery.tsx": $$$$$$20,
    "deco-sites/interdental/sections/Images/ShoppableBanner.tsx": $$$$$$21,
    "deco-sites/interdental/sections/Institutional/AsideMenu.tsx": $$$$$$22,
    "deco-sites/interdental/sections/Institutional/Institutional.tsx": $$$$$$23,
    "deco-sites/interdental/sections/Institutional/InstitutionalContent.tsx":
      $$$$$$24,
    "deco-sites/interdental/sections/Layout/Container.tsx": $$$$$$25,
    "deco-sites/interdental/sections/Layout/Flex.tsx": $$$$$$26,
    "deco-sites/interdental/sections/Layout/Grid.tsx": $$$$$$27,
    "deco-sites/interdental/sections/Layout/GridItem.tsx": $$$$$$28,
    "deco-sites/interdental/sections/Links/LinkTree.tsx": $$$$$$29,
    "deco-sites/interdental/sections/Links/Shortcuts.tsx": $$$$$$30,
    "deco-sites/interdental/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$31,
    "deco-sites/interdental/sections/Miscellaneous/CookieConsent.tsx": $$$$$$32,
    "deco-sites/interdental/sections/Miscellaneous/Form.tsx": $$$$$$33,
    "deco-sites/interdental/sections/Newsletter/Newsletter.tsx": $$$$$$34,
    "deco-sites/interdental/sections/Product/BuyTogether.tsx": $$$$$$35,
    "deco-sites/interdental/sections/Product/FeaturedProductShelf.tsx":
      $$$$$$36,
    "deco-sites/interdental/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$37,
    "deco-sites/interdental/sections/Product/ImageGallerySlider.tsx": $$$$$$38,
    "deco-sites/interdental/sections/Product/NotFound.tsx": $$$$$$39,
    "deco-sites/interdental/sections/Product/NotFoundChallenge.tsx": $$$$$$40,
    "deco-sites/interdental/sections/Product/ProductAttachments.tsx": $$$$$$41,
    "deco-sites/interdental/sections/Product/ProductDescription.tsx": $$$$$$42,
    "deco-sites/interdental/sections/Product/ProductFlag.tsx": $$$$$$43,
    "deco-sites/interdental/sections/Product/ProductInfo.tsx": $$$$$$44,
    "deco-sites/interdental/sections/Product/ProductShelf.tsx": $$$$$$45,
    "deco-sites/interdental/sections/Product/ProductShelfTabbed.tsx": $$$$$$46,
    "deco-sites/interdental/sections/Product/ProductSpecifications.tsx":
      $$$$$$47,
    "deco-sites/interdental/sections/Product/SearchResult.tsx": $$$$$$48,
    "deco-sites/interdental/sections/Product/Wishlist.tsx": $$$$$$49,
    "deco-sites/interdental/sections/SeoText/SeoText.tsx": $$$$$$51,
    "deco-sites/interdental/sections/SeoTextAndBanner/SeoTextAndBanner.tsx":
      $$$$$$50,
    "deco-sites/interdental/sections/Social/InstagramPosts.tsx": $$$$$$52,
    "deco-sites/interdental/sections/Social/WhatsApp.tsx": $$$$$$53,
    "deco-sites/interdental/sections/Theme/Theme.tsx": $$$$$$54,
  },
  "actions": {
    "deco-sites/interdental/actions/getProductAttachments.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/interdental/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/interdental/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/interdental",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
